source 'https://rubygems.org'
ruby '2.3.1'

gem 'aws-sdk'
gem 'bundler', '~> 1.13'
gem 'mongoid', '~> 6.0'
gem 'mongoid-paperclip', require: 'mongoid_paperclip'
gem 'mongoid_search'
gem 'mongoid_taggable', git: 'https://github.com/wilkerlucio/mongoid_taggable.git'
gem 'rails', '~> 5.0'
gem 'rake'
gem 'thin'

group :test, :development do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'foreman'
  gem 'hoe'
  gem 'rr'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'simplecov'
  gem 'spork'
  gem 'webrat'
end
